'''
Created on 06-Dec-2017

@author: cdot
'''
TIMEOUT=22
RETRIES=1
DEFAULT=0  
DEFAULT_STR=""
DEFAULT_LIST=[]
WSS_TX_DIR=2
WSS_RX_DIR=1   
MAX_RACKS=5
MAX_SUBRACKS=3 
#Card State
ACTIVE='1'
READY='2'
#Amplifier Type for cardType=4
PA=2
BA=1
#CardType and CardSubType
AMPLIFER=[4,0]
MPN=[1,1]
#CardType,CardSubType,DirectionOffset
WSS219=[9,0,20]  
WSS2120=[13,0,20] 
WSS12=[8,0]
#CardType,CardSubType,DirectionOffset
WSS19=[99,0,10] 
#NODE TYPE
DEFAULT=0
TE=1
Amplifier=2
SUTEEVRA=4
FOADM=5
ROADM2=6
HUB=7
CDC=8
#NODE DEGREE
TWO_D_NODE=2
#ERROR STATE
NO_ERROR=0
GNE_NOT_AVAILABLE=1
UNABLE_TO_GET_SUBAGENTINFO=2
END_IP_NOT_FOUND=3
EMPTY_WSS_DIR_CONFIG=4
GIVEN_DIR_CARD_UNAVAILABLE=5
GET_REQUEST_FAILED=6
TPN_CARD_DETAIL_NOT_FOUND=7